// <auto-generated>
//     此代码由 NodeDataAutoSync 自动生成。
// </auto-generated>

using System.Collections.Generic;
using UnityEngine;

namespace FlowyGraph
{
    public partial class AutoGenNodeDataModule
    {
        [SerializeField] public NodeDataList<global::FlowyGraph.BranchNodeData> BranchNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.CheckFloatValueNodeData> CheckFloatValueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.CombineNodeData> CombineNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.DelayNodeData> DelayNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.EndNodeData> EndNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.LockNodeData> LockNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.OnlyPassOnceNodeData> OnlyPassOnceNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.PassFirstOneNodeData> PassFirstOneNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.RandomDelayNodeData> RandomDelayNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.ResetBranchValueNodeData> ResetBranchValueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.ResetFloatValueNodeData> ResetFloatValueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.RunGraphNodeData> RunGraphNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.AddItemNodeData> AddItemNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.CameraFocusCancelNodeData> CameraFocusCancelNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.CameraFocusNodeData> CameraFocusNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.CharacterMoveNodeData> CharacterMoveNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.CharacterVisualStateNodeData> CharacterVisualStateNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.CheckItemNodeData> CheckItemNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.ChooseNodeData> ChooseNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.DiceCheckNodeData> DiceCheckNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.MessageBubbleNodeData> MessageBubbleNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.MonologueNodeData> MonologueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.RemoveItemNodeData> RemoveItemNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.Sample.SetCharacterNodeData> SetCharacterNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.SendSignalNodeData> SendSignalNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.SetBranchValueNodeData> SetBranchValueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.SetFloatValueNodeData> SetFloatValueNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.StartNodeData> StartNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.TimerNodeData> TimerNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.WaitAllOverNodeData> WaitAllOverNodeDataList;
        [SerializeField] public NodeDataList<global::FlowyGraph.WaitSignalNodeData> WaitSignalNodeDataList;
    }
}
